version: "3.9"

services:
  gogpt-spa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gogpt-spa
    restart: unless-stopped
    networks:
      - nginxproxyman

networks:
  nginxproxyman:
    external: true
