version: "3.9"

services:
  gogpt-spa-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: gogpt-spa-dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - nginxproxyman

networks:
  nginxproxyman:
    external: true

volumes:
  node_modules:
